#! /bin/sh
 
#### AUTOSTART ####

xsetroot -cursor_name left_ptr &
dunst &
mpd-notify &
xautolock -time 10 -locker slimlock &
feh --bg-scale /usr/share/wallpapers/Gray.png  &
synclient TapButton1=1 TapButton2=3 TapButton3=2 & #For laptop touchpad
xset -b & #For annoying beeping sounds
sxhkd & 
picom &
exec ~/.config/polybar/simple/launch.sh &

#### WORKSPACES AND BORDERS ####
 
#Monitor allocation and their workspaces
bspc monitor -d One Two Three Four Five Six
 
#Border gaps,width, and padding
bspc config border_width         2
bspc config window_gap          25
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius       15
 
bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         20
bspc config right_padding        20

bspc rule -a Firefox state=floating
bspc rule -a Virt-manager state=floating
bspc rule -a Virt-Manager state=floating
bspc rule -a rofi state=floating
bspc rule -a * state=floating
bspc rule -a kitty state=floating
bspc rule -a virt-manager state=floating
bspc rule -a firefox state=floating
#bspc rule -a kitty desktop='^1' follow=on
#bspc rule -a Subl3 desktop='^2' follow=on
#bspc rule -a Firefox desktop='^3' follow=on
#bspc rule -a Thunar desktop='^4' follow=on
#bspc rule -a Evince desktop='^5'follow=on
 
#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config normal_border_color '#000000'
bspc config active_border_color '#000000'
bspc config focused_border_color '#000000'
